name       : shadow
version    : '4.13'
release    : 23
source     :
    - https://github.com/shadow-maint/shadow/releases/download/4.13/shadow-4.13.tar.xz : 9afe245d79a2e7caac5f1ed62519b17416b057ec89df316df1c3935502f9dd2c
license    : BSD-3-Clause
component  : system.base
summary    : login and password tools
description: |
    Utilities for managing shadow password files and user/group accounts
builddeps  :
    - pkgconfig(libacl)
    - pkgconfig(libattr)
    - pkgconfig(libeconf)
    - pkgconfig(libxcrypt)
setup      : |
    %configure --enable-vendordir=/usr/share/defaults/etc/ \
               --with-yescrypt
build      : |
    %make
install    : |
    %make_install

    # Get rid of groups
    find $installdir/usr/share/man -type f -name groups.1 | xargs rm -frv
    rm -fv $installdir/usr/bin/groups

    # Set up stateless support for pam.d
    rm -rf $installdir/etc/pam.d
    install -dm00755 $installdir/usr/share/defaults/etc/pam.d
    install -m00644 $pkgfiles/pam.d/* -t $installdir/usr/share/defaults/etc/pam.d

    # set new user HOME dirs to drwxr-x--x
    # sshd `StrictModes yes` default does not allow group writable $HOME, hence g=rx
    # samba usershare functionality requires o=x set
    sed -i 's/^#HOME_MODE\t0700$/HOME_MODE\t0751/g' $installdir/etc/login.defs
    grep -Hn -E '^HOME_MODE' $installdir/etc/login.defs

    # Install compat links T10615
    for TOP in {bin,sbin}; do
        install -D -d -m 00755 $installdir/$TOP
        pushd $installdir/usr/$TOP
        for FILE in *; do
            ln -sv /usr/$TOP/$FILE $installdir/$TOP/$FILE
        done
        popd
    done
