name       : shadow
version    : '4.13'
release    : 21
source     :
    - https://github.com/shadow-maint/shadow/releases/download/4.13/shadow-4.13.tar.xz : 9afe245d79a2e7caac5f1ed62519b17416b057ec89df316df1c3935502f9dd2c
license    : BSD-3-Clause
component  : system.base
summary    : login and password tools
description: |
    Utilities for managing shadow password files and user/group accounts
builddeps  :
    - pkgconfig(libxcrypt)
    - acl-devel
    - attr-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install

    # Put passwd somewhere sensible
    mv -fv $installdir/usr/bin/passwd $installdir/bin/

    # Get rid of groups
    find $installdir/usr/share/man -type f -name groups.1 | xargs rm -frv
    rm -fv $installdir/bin/groups

    # Set up stateless support for pam.d
    rm -rf $installdir/etc/pam.d
    install -dm00755 $installdir/usr/share/defaults/etc/pam.d
    install -m00644 $pkgfiles/pam.d/* -t $installdir/usr/share/defaults/etc/pam.d

    # set new user HOME dirs to drwx------ per T10379
    # NB: The sshd `StrictModes yes` default does not allow group writable $HOME
    sed -i 's/^#HOME_MODE\t0700$/HOME_MODE\t0700/g' $installdir/etc/login.defs
    grep -Hn -E '^HOME_MODE' $installdir/etc/login.defs
