name       : shadow
version    : 4.8.1
release    : 16
source     :
    - https://github.com/shadow-maint/shadow/releases/download/4.8.1/shadow-4.8.1.tar.xz : a3ad4630bdc41372f02a647278a8c3514844295d36eefe68ece6c3a641c1ae62
license    : BSD-3-Clause
component  : system.base
summary    : login and password tools
description: |
    Utilities for managing shadow password files and user/group accounts
builddeps  :
    - acl-devel
    - attr-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install

    # Put passwd somewhere sensible
    mv -fv $installdir/usr/bin/passwd $installdir/bin/

    # Get rid of groups
    find $installdir/usr/share/man -type f -name groups.1 | xargs rm -frv
    rm -fv $installdir/bin/groups

    rm -rf $installdir/etc/pam.d
    install -dm00755 $installdir/usr/share/defaults/etc/pam.d
    install -m00644 $pkgfiles/pam.d/* -t $installdir/usr/share/defaults/etc/pam.d
