name       : shadow
version    : 4.5
release    : 9
source     :
    - https://github.com/shadow-maint/shadow/releases/download/4.5/shadow-4.5.tar.xz : fc8c858381ad577a5c25ff5beb6ee60a34f8719c73e4e7c61e74188b4e54b741
license    : BSD-3-Clause # BSD-style
component  : system.base
summary    : login and password tools
description: |
    Utilities for managing shadow password files and user/group accounts
builddeps  :
    - acl-devel
    - attr-devel
setup      : |
    %patch -p1 < $pkgfiles/security/cve-2018-7169.patch
    %configure --prefix=/usr --sysconfdir=/etc
build      : |
    %make
install    : |
    %make_install

    # Put passwd somewhere sensible
    mv -fv $installdir/usr/bin/passwd $installdir/bin/

    # Get rid of groups
    find $installdir/usr/share/man -type f -name groups.1 | xargs rm -frv
    rm -fv $installdir/bin/groups

    install -dm 755 $installdir/etc/pam.d
    install -m 644 $pkgfiles/pam.d/* -t $installdir/etc/pam.d
