name       : shadow
version    : 4.6
release    : 13
source     :
    - https://github.com/shadow-maint/shadow/releases/download/4.6/shadow-4.6.tar.xz : 0998c8d84242a231ab0acb7f8613927ff5bcff095f8aa6b79478893a03f05583
license    : BSD-3-Clause
component  : system.base
summary    : login and password tools
description: |
    Utilities for managing shadow password files and user/group accounts
builddeps  :
    - acl-devel
    - attr-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install

    # Put passwd somewhere sensible
    mv -fv $installdir/usr/bin/passwd $installdir/bin/

    # Get rid of groups
    find $installdir/usr/share/man -type f -name groups.1 | xargs rm -frv
    rm -fv $installdir/bin/groups

    rm -rf $installdir/etc/pam.d
    install -dm00755 $installdir/usr/share/defaults/etc/pam.d
    install -m00644 $pkgfiles/pam.d/* -t $installdir/usr/share/defaults/etc/pam.d
